name: Fetch and Process SBI Forex Rates

on:
  schedule:
    - cron: "30 0,6,12,18 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    container:
      image: python:3.13-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            gcc \
            g++ \
            wget \
            curl \
            ca-certificates \
            && rm -rf /var/lib/apt/lists/*

      - name: Set up Python environment
        run: |
          python -m pip install --upgrade pip
          pip install -r cron/requirements.txt

      - name: Fetch and process SBI forex rates
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd cron
          python fetch_and_fill_from_url.py

      - name: Notify on failure
        if: failure()
        run: |
          echo "SBI Forex rates processing failed at $(date)"
          # You can add notification logic here (e.g., send email, Slack message, etc.)
