name: Keep API Warm

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  keep-warm:
    runs-on: ubuntu-latest

    steps:
      - name: Keep API warm
        env:
          FOREX_API_HOST: ${{ secrets.FOREX_API_HOST }}
        run: |
          # Get current date in DD-MM-YYYY format
          CURRENT_DATE=$(date +%d-%m-%Y)

          # Construct the API URL
          API_URL="${FOREX_API_HOST}/?date=${CURRENT_DATE}"

          # Make the GET request with curl and capture HTTP status
          response=$(curl -s -w "\n%{http_code}" --max-time 10 "$API_URL" || echo "000")
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | head -n -1)

          echo "HTTP Status Code: $http_code"

          # Fail the job if the request was not successful (non-2xx)
          if [[ $http_code =~ ^2[0-9][0-9]$ ]]; then
            echo "✅ API warmup successful"
            echo "Response preview: $(echo "$response_body" | head -c 25)..."
          else
            echo "ERROR: API warmup returned non-2xx status code: $http_code"
            echo "❌ API warmup failed"
            echo "Response: $response_body"
            exit 1
          fi
